version: '3.5'

services:

  frontend:
    image: frontend-example
    environment:
      - API_URL=http://localhost:80/api
    networks:
      - frontend
    container_name: frontend

  backend:
    image: backend-example
    environment:
      - REDIS=redis
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=asdf1234
    volumes:
      - ./logs.txt:/app/logs.txt
    networks:
      - backend
    container_name: backend
    depends_on:
      - redis
      - db

  redis:
    image: redis:6.0
    networks:
      - backend
    container_name: redis

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - /home/davido/db:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=asdf1234
    container_name: db
  
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - frontend
      - backend
    container_name: nginx
    depends_on:
      - frontend
      - backend


networks:
  backend:
    name: backend
  frontend:
    name: frontend
